### ISSUE TITLE
Unhandled promise reject exit application

### ISSUE THREAD

**Issue by morDabush** [gajus/async-request#3]
hello i found some minor bug at your code
missed reject on promise cause application close

 return new Promise((resolve, reject) => {
            Arequest.validateOptions(options);

            options = _.assign({url: url}, options, defaultOptions);

            options = Arequest.mapOptions(options);

            request(options, (error, response) => {
                if (error) {
                    return reject(error);
                }

                resolve({
                    statusCode: response.statusCode,
                    headers: response.headers,
                    body: response.body
                });
            });
        });

**Comment by gajus** [comment]
Please see depreciation notice. https://github.com/gajus/async-request#deprecated
